services:
  - type: web
    name: salary-management-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm prisma generate && pnpm prisma migrate deploy && pnpm tsx prisma/seed.ts && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/data/dev.db
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
